// Code generated by protoc-gen-go. DO NOT EDIT.
// source: door.proto

/*
Package door is a generated protocol buffer package.

It is generated from these files:
	door.proto

It has these top-level messages:
	Door
	User
*/
package door

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Door struct {
	Type    int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	User    *User  `protobuf:"bytes,11,opt,name=user" json:"user,omitempty"`
}

func (m *Door) Reset()                    { *m = Door{} }
func (m *Door) String() string            { return proto.CompactTextString(m) }
func (*Door) ProtoMessage()               {}
func (*Door) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Door) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Door) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Door) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Door) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Nick  string `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Door)(nil), "Door")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("door.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x45, 0x15, 0x48, 0x81, 0xb8, 0x5b, 0xc4, 0x10, 0xb6, 0xa8, 0x53, 0xa6, 0x0a, 0xc1, 0x15,
	0x38, 0x81, 0x25, 0x2e, 0x40, 0xf0, 0x80, 0x2a, 0xd5, 0x95, 0x93, 0x0e, 0xdc, 0x1e, 0xc5, 0x15,
	0xdb, 0x7b, 0x1e, 0xfc, 0x3e, 0xc0, 0x9b, 0x59, 0xc6, 0x45, 0xb8, 0xf2, 0x40, 0x60, 0x1f, 0xcc,
	0xe2, 0x3d, 0xd8, 0xfa, 0x5d, 0x28, 0x98, 0x68, 0x52, 0x87, 0xca, 0x3e, 0xc0, 0xb1, 0xac, 0x39,
	0x53, 0x29, 0x61, 0x17, 0x4d, 0x3a, 0xe1, 0x5f, 0xfd, 0x19, 0x3a, 0x12, 0x61, 0x09, 0xfb, 0x68,
	0x92, 0xc3, 0x4d, 0xfc, 0x05, 0xec, 0x5a, 0x48, 0x42, 0x1f, 0x4d, 0xea, 0x6f, 0xdd, 0xf8, 0x2c,
	0x24, 0xa8, 0xa7, 0xe1, 0x0a, 0xb6, 0x59, 0xcb, 0xcc, 0x9f, 0x3c, 0x69, 0xc6, 0xa1, 0x72, 0x7b,
	0x56, 0x79, 0xa2, 0x59, 0x23, 0x0e, 0x37, 0x79, 0x1d, 0x74, 0xdf, 0xfd, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x2a, 0xd6, 0xab, 0x38, 0xad, 0x00, 0x00, 0x00,
}
