// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Success bool   `protobuf:"varint,1,opt,name=Success,json=success" json:"Success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=Error,json=error" json:"Error,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=Data,json=data" json:"Data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Message) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe5, 0x62, 0xf7, 0x85, 0x08,
	0x08, 0x49, 0x70, 0xb1, 0x07, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x04, 0xb1, 0x17, 0x43, 0xb8, 0x42, 0x22, 0x5c, 0xac, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xac, 0xa9, 0x20, 0x8e, 0x90, 0x10, 0x17, 0x8b, 0x4b, 0x62,
	0x49, 0xa2, 0x04, 0x33, 0x58, 0x90, 0x25, 0x25, 0xb1, 0x24, 0x31, 0x89, 0x0d, 0x6c, 0xaa, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x84, 0x72, 0xb4, 0x66, 0x00, 0x00, 0x00,
}
